#!/bin/sh

CARD="timecard"
if [ -n "$1" ]; then
    CARD=$1
    shift
fi

if [ -n "$1" ]; then
    python timecard.py -f cards/$CARD.log analyze "$1"
else
    python timecard.py -f cards/$CARD.log analyze
fi
