#!/bin/sh

CARD="timecard"
if [ -n "$2" ]; then
    CARD=$1
    shift
fi

if [ -n "$1" ]; then
    python timecard.py -f cards/$CARD.log summarize "$1"
else
    python timecard.py -f cards/$CARD.log summarize
fi
